#!/usr/bin/env bash

# Dev paths
dev=$HOME/dev
src=$dev/src

# Dev path commands
_dev_completion() { _files -W $dev; }
dev() { cd $dev/$1; }
compdef _dev_completion dev

_src_completion() { _files -W $src; }
src() { cd $src/$1; }
compdef _src_completion src

# Misc paths
dotfiles=$HOME/.dotfiles
dotfiles() { cd $dotfiles; }
