#!/usr/bin/env bash

# Automatically load aliases from this file

source $HOME/.dotfiles/libs/common


ack-syn() {
    echo $@
    FILE=$1 && shift
    less $FILE|ack --color -C 3 $@|less
}


# Fix the last command...
if cmd_exists thefuck; then
    eval "$(thefuck --alias fuck)";
    alias ugh='fuck'
    # Colemak homerow spam
    alias arst='fuck'; alias oien='fuck'
    # Qwerty homerow spam
    alias asdf='fuck'; alias lkj='fuck'
fi


alias ack='ack-grep --color'
alias a='autorandr'
alias ara='autorandr'
alias d-c='docker-compose'
alias dropbox-encfs='encfs ~/Dropbox/Sync/Security/encfs ~/Dropbox-encfs'
alias grep='grep --color=always'
alias less='less -R'
alias rm='rm -I'
alias watch-files=entr
if cmd_exists nvim; then alias vim=nvim; fi
if cmd_exists hub; then alias git=hub; fi
