#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "molokai"
    background = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    statusline_display_mode = false

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'checkers'

[[layers]]
name = 'colorscheme'

[[layers]]
name = 'ctrlp'

[[layers]]
name = 'debug'

[[layers]]
name = 'default'

[[layers]]
name = 'denite'

[[layers]]
name = 'editing'

[[layers]]
name = 'git'

[[layers]]
name = 'ui'

[[layers]]
name = 'unite'

[[layers]]
name = 'lang#Dockerfile'

[[layers]]
name = 'lang#elixir'

[[layers]]
name = 'lang#go'

[[layers]]
name = 'lang#html'

[[layers]]
name = 'lang#javascript'

[[layers]]
name = 'lang#lua'

[[layers]]
name = 'lang#markdown'

[[layers]]
name = 'lang#ocaml'

[[layers]]
name = 'lang#python'

[[layers]]
name = 'lang#ruby'

[[layers]]
name = 'lang#typescript'

[[layers]]
name = 'lang#vim'

[[layers]]
name = 'lang#vim'

[[layers]]
name = 'lang#xml'

[[layers]]
name = 'lang#json'
